remote_theme: jekyll/minima@master

title: Jan Verbesselt
description: Earth Observation expert at the interface of science, policy, and application.

minima:
  skin: auto

author:
  name: Jan Verbesselt
  email: jan.verbesselt[@]belspo.be

markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-feed
  - jekyll-remote-theme

url: "https://janverbesselt.github.io"
baseurl: ""

goatcounter_code: "janverbesselt"